spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: <Login User to SMTP server>
    password: <Login password to SMTP server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true